[package]
name = "linux_virtual_joystick"
version = "0.1.0"
authors = ["Abe Zukor <abezukor@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
anyhow = "1.0.82"
evdev = "0.12.1"
eframe = "0.27.2"
